# config.yaml file

system_config:
  backend: sge # ubuntu
  conda: conda
  environment: separability
  threads: 5

data:
  datapath: /data/cluster/users/motzkus/data/imagenet/    # /data/cluster/users/motzkus/data/VOC2012/     imagenet
  dataname: imagenet  # VOC2012    imagenet
  datasetobject: MyImagenetDataset   # VOC2012Dataset   MyImagenetDataset
  partition: val  # might delete to enable simultaneous computation on train/val dataset
  batchsize: 50

model:
  modelpath: /data/cluster/users/motzkus/models/vgg16bn_imagenet/pytorch_model/model.pt # /data/cluster/users/motzkus/models/resnet18_voc2012/pytorch_model/model.pt  #  /data/cluster/users/motzkus/models/vgg16_voc2012/pytorch_model/model.pt
  modelname: vgg16bn     #vgg16      # resnet18    #vgg16bn
  modeltype: pytorch

dirs:
  logdir: logs-experiments/
  scriptdir: scripts-experiments/
  explanationdir: /data/cluster/users/motzkus/relevance_maps
  outputdir: /data/cluster/users/motzkus/results

layers:
#  - conv1
#  - conv3
#  - conv5
#  - conv8
#  - conv11
#  - conv13
#  - linear1
#  - linear2
#  - linear3
#  - block1_conv1
#  - block2_conv1
#  - block3_conv1
#  - block4_conv1
#  - block5_conv1
#  - fc1
#  - fc2
  - conv1     # input
  - conv4     # sec1.1
  - conv6     # sec2
  - conv9     # sec2.1
  - conv11    # sec3
  - conv14    # sec3.1
  - conv16    # sec4
  - conv19    # sec4.1
  - linear1

xai_methods:
#  - LRPZ
##  - LRPAlpha1Beta0
#  - LRPSequentialCompositeA
#  - LRPSequentialCompositeBFlat
#  - LRPGamma
#  - Gradient
#  - random
#  - Saliency
#  - SmoothGrad
#  - Deconvolution
#  - IntegratedGradients
#  - GradientXActivation
#  - GradCam
#  - DeepLift
  - epsilon
  - epsilon_gamma_box
  - epsilon_plus
#  - epsilon_plus_flat
  - epsilon_alpha2_beta1
#  - epsilon_alpha2_beta1_flat
  - alpha2_beta1
#  - alpha2_beta1_flat

classes:
  - all
#  - n02410509
#  - n03393912
#  - n04540053
#  - aeroplane
#  - person
#  - pottedplant
#  - sheep
#  - sofa
#  - train
#  - tvmonitor

quantifications:
#  - attribution_computation:
#      config:
#          memory_per_job: 10G # 10G  # 20
#  - attribution_localization:
#      config:
#          memory_per_job: 3G
#  - pixelflipping:
#      args:
#          percentages:
#            - 0.0
#            - 0.0002
#            - 0.0004
#            - 0.0006
#            - 0.0008
#            - 0.002
#            - 0.01
#            - 0.02
#            - 0.04
#            - 0.06
#            - 0.08
#            - 0.1
#            - 0.2
#            - 0.3
#            - 0.4
#            - 0.5
#            - 0.6
#            - 0.7
#            - 0.8
#            - 0.9
#          distribution: inpaint_ns   # uniform, gaussian, inpaint_telea, inpaint_ns, uniform_region, gaussian_region
#      config:
#          memory_per_job: 5G
#  - pointing_game:
#      args:
#         gaussian_blur: True
#      config:
#          memory_per_job: 3G
  - model_parameter_randomization:
      args:
          max_index: 300
          distance_measures:
            - cosine
            - ssim
            - spearman
            - spearman_abs
            - hog
          setting: independent   # top_down   bottom_up   independent
      config:
          memory_per_job: 15G  # 15G # 40G # 7G
#  - one_class_separability:
#      args:
#      config:
#          memory_per_job: 5G
#  - separability:
#      args:
#      config:
#          memory_per_job: 10G
#  - manifold_outlier_pixelflipping_experiment:
#      args:
#          percentages:
#            - 0.0
#            - 0.0002
#            - 0.0004
#            - 0.0006
#            - 0.0008
#            - 0.002
#            - 0.01
#            - 0.02
#            - 0.04
#            - 0.06
#            - 0.08
#            - 0.1
#            - 0.2
#            - 0.3
#            - 0.4
#            - 0.5
#            - 0.6
#            - 0.7
#            - 0.8
#            - 0.9
#          distribution: uniform   # uniform, gaussian, inpaint_telea, inpaint_ns, uniform_region, gaussian_region
#      config:
#          memory_per_job: 4G
#  - tsne_manifold:
#      args:
#          percentages:
#              - 0.0
#              - 0.0002
#              - 0.0004
#              - 0.0006
#              - 0.0008
#              - 0.002
#              - 0.01
#              - 0.02
#              - 0.04
#              - 0.06
#              - 0.08
#              - 0.1
#              - 0.2
#              - 0.3
#              - 0.4
#              - 0.5
#              - 0.6
#              - 0.7
#              - 0.8
#              - 0.9
#          distribution: inpaint_ns   # uniform, gaussian, inpaint_telea, inpaint_ns, uniform_region, gaussian_region
#      config:
#          memory_per_job: 3G
#  - tsne_manifold_one_class:
#      args:
#          percentages:
#              - 0.0
##              - 0.0002
##              - 0.0004
##              - 0.0006
##              - 0.0008
#              - 0.002
##              - 0.01
#              - 0.02
##              - 0.04
##              - 0.06
##              - 0.08
#              - 0.1
#              - 0.2
#              # - 0.3
#              - 0.5
#              # - 0.6
#              - 0.7
#              # - 0.8
#              - 0.9
#          distribution: uniform   # uniform, gaussian, inpaint_telea, inpaint_ns, uniform_region, gaussian_region
#      config:
#          memory_per_job: 3G
#  - activation_eval:
#        args:
#            percentages:
#              - 0.0
#              - 0.0002
#              - 0.0004
#              - 0.0006
#              - 0.0008
#              - 0.002
#              - 0.01
#              - 0.02
#              - 0.04
#              - 0.06
#              - 0.08
#              - 0.1
#              - 0.2
#              - 0.3
#              - 0.5
#              - 0.7
#              - 0.9
#            distribution: inpaint_ns   # uniform, gaussian, inpaint_telea, inpaint_ns, uniform_region, gaussian_region
#        config:
#            memory_per_job: 3G