# config.yaml file

system_config:
  backend: sge # ubuntu
  conda: conda
  environment: separability
  memory_per_job: 15G
  threads: 5

data:
  datapath: /data/cluster/users/motzkus/data/VOC2012/
  dataname: voc2012
  datasetobject: VOC2012Dataset
  partition: val  # might delete to enable simultaneous computation on train/val dataset
  batchsize: 50

model:
  modelpath: /data/cluster/users/motzkus/models/vgg16_voc2012/model
  modelname: vgg16
  modeltype: tensorflow

dirs:
  logdir: logs-quantification/
  scriptdir: scripts-quantification/
  explanationdir: /data/cluster/users/motzkus/relevance_maps
  outputdir: /data/cluster/users/motzkus/results

layers:
  - input_1
  - block1_conv1
  - block2_conv1
  - block3_conv1
  - block4_conv1
  - block5_conv1
  - fc1
  - fc2

xai_methods:
  - LRPZ
  - LRPAlpha1Beta0
  #- LRPSequentialCompositeA
  - LRPSequentialCompositeBFlat
  - LRPGamma
  - Gradient
  - SmoothGrad

classes:
  - all

quantifications:
  - relevance_computation
